pipeline {
    
agent none

environment {
    DOCKER_IMAGE = "shilpa1819/k8s:${BUILD_NUMBER}"
}

stages {

    stage('Checkout Code') {
        agent { label 'docker-agent' }
        steps {
            checkout scm
        }
    }

    stage('Build Docker Image') {
        agent { label 'docker-agent' }
        steps {
            sh 'docker build -t $DOCKER_IMAGE -f docker/Dockerfile .'
        }
    }

    stage('Push Image to DockerHub') {
    agent { label 'docker-agent' }
    steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
            sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_IMAGE
            '''
        }
    }
}

    stage('Deploy to Kubernetes') {
        agent { label 'k8s-agent' }
        steps {
            sh 'kubectl set image deployment/node-app node-container=$DOCKER_IMAGE'
        }
    }

}

}
