pipeline {

```
agent none

stages {

    stage('Checkout Code') {
        agent { label 'docker-agent' }
        steps {
            checkout scm
        }
    }

    stage('Build Docker Image') {
        agent { label 'docker-agent' }
        steps {
            sh 'docker build -t shilpa1819/k8s:latest -f docker/Dockerfile .'
        }
    }

    stage('Push Docker Image') {
        agent { label 'docker-agent' }
        steps {
            sh 'docker push shilpa1819/k8s/node-app:latest'
        }
    }

    stage('Deploy to Kubernetes') {
        agent { label 'k8s-agent' }
        steps {
            sh 'kubectl apply -f k8s/deployment.yaml'
            sh 'kubectl apply -f k8s/service.yaml'
        }
    }

}
```

}

